#! /usr/bin/env ruby

SRC_PATH = File.expand_path('~/src')

prefix = ARGV[0]

repos = Dir.glob(File.join(SRC_PATH, '*')).map{|r| r.split('/').last}

if prefix.nil? || prefix.empty?
  puts "Available repos:"
  repos.sort.each {|r| puts "    #{r}"}
  exit 1
end

results = repos.select{|r| r.index(prefix) == 0}
exact = results.detect{|r| r == prefix}

if exact
  puts File.join(SRC_PATH, exact)
  exit 0
elsif results.size == 1
  puts File.join(SRC_PATH, results.first)
  exit 0
elsif results.empty?
  puts "  No repos start with '#{prefix}'"
  exit 1
elsif results.size > 1
  puts "  Multiple repos match:"
  results.sort.each {|s| puts "    #{s}"}
  exit 1
else
  puts "  Well this was unexpected."
  puts "  Exact: #{exact.inspect}."
  puts "  Results: #{results.inspect}."
end
